set(F4SEVRTEMPLATE_VERSION_MAJOR 0)
set(F4SEVRTEMPLATE_VERSION_MINOR 1)
set(F4SEVRTEMPLATE_VERSION_PATCH 1)

set(F4_VERSION_MAJOR 1)
set(F4_VERSION_MINOR 2)
set(F4_VERSION_PATCH 72)

math(
	EXPR
	F4_VERSION_PACKED
	"((${F4_VERSION_MAJOR} & 0xFF) << 24) | ((${F4_VERSION_MINOR} & 0xFF) << 16) | ((${F4_VERSION_PATCH} & 0xFFF) << 4)"
	OUTPUT_FORMAT
		HEXADECIMAL
)
